apiVersion: v1
kind: ConfigMap

metadata:
  name: tf-serving-monitoring
  namespace: serving

data:
  monitoring.config: |
    prometheus_config {
      enable: true
      path: "/monitoring/prometheus/metrics"
    }
