FROM tensorflow/serving:2.16.1

RUN groupadd --gid 10001 appuser \
    && useradd --uid 10001 \
               --gid 10001 \
               --create-home \
               appuser

COPY --chown=10001:10001 saved_model/ /models/cifar10_model/1/

ENV MODEL_NAME=cifar10_model

EXPOSE 8501 8500

USER 10001:10001
